"""Runtime-backed continuation logprob scoring helpers.

Purpose:
    Provide runtime-backed continuation logprob scoring helpers used by
    higher-level scoring components.

Architectural role:
    Internal inference adapter layer below engine scoring and above
    model-runtime primitives.

"""

from __future__ import annotations

from dataclasses import dataclass

import torch

from answer_engineering.inference.model_types import (
    TokenGenerationRuntime,
)
from answer_engineering.inference.prompting import prompt_prefix


@dataclass(slots=True)
class LogprobResult:
    """Structured output of one runtime scoring call.

    Purpose:
        Carry the aggregate logprob and optional per-token details produced when
        the runtime scores one continuation against a prefix.

    Architectural role:
        Runtime-adapter value object returned by inference scoring helpers and
        consumed by engine-side scoring code.

    """

    logprob_sum: float
    token_logprobs: list[float] | None
    token_ids: list[int] | None


@dataclass(frozen=True, slots=True)
class RuntimeLogprobScorer:
    """Runtime-backed logprob scorer for continuations.

    Purpose:
        Score the logprobs of continuations against a prefix using a runtime.

    Architectural role:
        Inference adapter implementing logprob scoring logic using the runtime's
        forward method, for use by engine scoring code.

    """

    runtime: TokenGenerationRuntime

    def score_continuations_batch(
        self,
        *,
        prefix_ids: list[int],
        continuation_ids_list: list[list[int]],
        return_token_details: bool = False,
    ) -> list[LogprobResult]:
        """Score multiple continuations against one prefix in a single batch.

        Purpose:
            Compute mean log-probability scores for candidate continuation
            strings under the materialized language model.

        Architectural role:
            Model-scoring adapter between engine scoring code and the inference
            runtime. It hides tokenizer padding, prefix tensor construction, and
            backend forward details from proposal scorers.

        Inputs (architectural provenance):
            Receives a shared token prefix from scoring tasks and continuation
            texts generated by patch-candidate construction.

        Outputs (downstream usage):
            Returns one numeric score per continuation in the original order,
            consumed by logits/model-backed scoring.

        Invariants/constraints:
            The runtime is forced into eval mode before scoring. Empty
            continuation batches return an empty list, and tokenization/padding
            details stay local to this adapter.

        """
        runtime = self.runtime
        if not continuation_ids_list:
            return list()

        tok = runtime.text_codec()
        effective_prefix = prompt_prefix.normalize_prefix_ids(
            tokenizer=tok, prefix_ids=prefix_ids
        )

        pad_token_id = tok.pad_token_id
        if pad_token_id is None:
            pad_token_id = tok.eos_token_id
        if isinstance(pad_token_id, list):
            pad_token_id = pad_token_id[0] if pad_token_id else None
        if pad_token_id is None:
            raise ValueError(
                "tokenizer must define pad_token_id or eos_token_id"
            )

        seqs = [[*effective_prefix, *cont] for cont in continuation_ids_list]
        lengths = [len(seq) for seq in seqs]
        max_len = max(lengths)

        padded: list[list[int]] = []
        masks: list[list[int]] = []
        for seq in seqs:
            pad_len = max_len - len(seq)
            padded.append([*seq, *([pad_token_id] * pad_len)])
            masks.append(([1] * len(seq)) + ([0] * pad_len))

        input_ids = torch.tensor(
            padded, dtype=torch.long, device=runtime.execution_device()
        )
        attn = torch.tensor(
            masks, dtype=torch.long, device=runtime.execution_device()
        )

        with torch.inference_mode():
            out = runtime.forward(
                input_ids=input_ids, attention_mask=attn, use_cache=False
            )
        logits = out.logits
        log_probs = torch.log_softmax(logits, dim=-1)

        results: list[LogprobResult] = []
        start = max(1, len(effective_prefix))
        for row, cont in enumerate(continuation_ids_list):
            total = 0.0
            per_token: list[float] = []
            for offset, token_id in enumerate(cont):
                pos = start + offset
                lp = float(log_probs[row, pos - 1, token_id].item())
                total += lp
                if return_token_details:
                    per_token.append(lp)
            results.append(
                LogprobResult(
                    logprob_sum=total,
                    token_logprobs=per_token if return_token_details else None,
                    token_ids=list(cont) if return_token_details else None,
                )
            )

        return results


__all__ = [
    "LogprobResult",
    "RuntimeLogprobScorer",
]
