"""Patch-application primitives for proposal materialization.

Purpose:
    Apply replace/insert/delete/noop operations against immutable document
    snapshots and compute resulting ``DocumentState`` values.

Architectural role:
    Runtime mutation primitive used by scoring and apply stages.

"""

from __future__ import annotations

from answer_engineering.engine.patching.proposals import PatchProposal
from answer_engineering.engine.runtime.runtime_types import (
    DocumentState,
    PatchOp,
)

_LEFT_TIGHT_PUNCT = ".,;:!?)]}"
_RIGHT_TIGHT_PUNCT = "([{"
_BILATERAL_TIGHT_MARKERS = "*_`~"


def _needs_left_space(left: str, first: str) -> bool:
    """Return whether inserted text needs a leading space against left context.

    Purpose:
        Preserve readable token boundaries when normalizing insert payloads.

    Architectural role:
        Low-level spacing heuristic used by patch canonicalization before apply.

    Inputs (architectural provenance):
        Receives the character immediately to the left of the insertion point
        and the first character of the payload.

    Outputs (downstream usage):
        Boolean guides whether ``normalize_insert_payload`` prepends a space.

    """
    left_char = left[-1:] if left else ""
    first_char = first[:1] if first else ""
    return bool(
        left_char
        and not left_char.isspace()
        and first_char
        and not first_char.isspace()
        and left_char not in _RIGHT_TIGHT_PUNCT
        and left_char not in _BILATERAL_TIGHT_MARKERS
        and first_char not in _LEFT_TIGHT_PUNCT
    )


def _needs_right_space(last: str, right: str) -> bool:
    """Return whether inserted or replaced text needs a trailing space against.

    Purpose:
        Prevent accidental token fusion at the right boundary of a normalized
        patch payload.

    Architectural role:
        Companion spacing heuristic for patch canonicalization.

    Inputs (architectural provenance):
        Receives the last character of the payload and the first character in
        the untouched right context.

    Outputs (downstream usage):
        Boolean guides whether normalization appends a space to the payload.

    """
    last_char = last[-1:] if last else ""
    right_char = right[:1] if right else ""
    return bool(
        right_char
        and not right_char.isspace()
        and right_char.isalnum()
        and last_char
        and not last_char.isspace()
        and last_char not in _RIGHT_TIGHT_PUNCT
    )


def normalize_insert_payload(text: str, pos: int, payload: str) -> str:
    """Normalize an insert payload against neighboring document text.

    Purpose:
        Trim and shape payload spacing so insert-before and insert-after edits
        keep natural word boundaries without over-normalizing punctuation.

    Architectural role:
        Canonicalization helper shared by proposal freezing and patch
        application.

    Inputs (architectural provenance):
        Uses the current document text, insertion position, and raw candidate
        payload generated by proposal logic.

    Outputs (downstream usage):
        Returns a spacing-normalized payload that can be hashed, compared, and
        applied deterministically.

    """
    if not payload:
        return payload
    out = payload
    left = text[pos - 1] if pos > 0 else ""
    right = text[pos] if 0 <= pos < len(text) else ""

    if _needs_left_space(left, out[0]):
        out = " " + out

    if _needs_right_space(out[-1], right):
        out = out + " "

    if left.isspace() and out.startswith(" "):
        out = out.lstrip(" ")
    if right.isspace() and out.endswith(" "):
        out = out.rstrip(" ")

    return out


def normalize_replace_payload(
    text: str, start: int, end: int, payload: str
) -> str:
    """Normalize a replacement payload for a concrete target span.

    Purpose:
        Canonicalize replacement text using the left/right context around the
        span so replacement proposals compare and apply consistently.

    Architectural role:
        Patch-normalization helper for replace operations.

    Inputs (architectural provenance):
        Receives full document text, target span, and raw replacement payload
        from proposal generation.

    Outputs (downstream usage):
        Returns the normalized replacement text stored on ``PatchProposal`` and
        used by apply/change-detection logic.

    """
    if not payload:
        return payload
    out = payload
    left = text[start - 1] if start > 0 else ""
    right = text[end] if 0 <= end < len(text) else ""

    if _needs_left_space(left, out[0]):
        out = " " + out
    if _needs_right_space(out[-1], right):
        out = out + " "

    if left.isspace() and out.startswith(" "):
        out = out.lstrip(" ")
    if right.isspace() and out.endswith(" "):
        out = out.rstrip(" ")

    return out


def _patch_error_context(doc: DocumentState, proposal: PatchProposal) -> str:
    span = proposal.span_abs
    text = doc.text
    if span is None:
        around = None
    else:
        start, end = span
        lo = max(0, start - 120)
        hi = min(len(text), end + 120)
        around = text[lo:hi]
    payload = (
        proposal.payload_norm
        if proposal.payload_norm is not None
        else proposal.payload
    )
    payload_preview = (payload or "")[:120]
    return (
        f"doc_len={len(text)}\n"
        f"  span_abs={proposal.span_abs}\n"
        f"  op={proposal.op.value}\n"
        f"  rule_id={proposal.rule_id}\n"
        f"  candidate_id={proposal.candidate_id}\n"
        f"  candidate_label={proposal.candidate_label}\n"
        f"  payload_preview={payload_preview!r}\n"
        f"  around_span={around!r}\n"
        f"  document_tail={text[-300:]!r}"
    )


def apply_patch(doc: DocumentState, proposal: PatchProposal) -> DocumentState:
    """Apply ``proposal`` to ``doc`` while preserving immutable state semantics.

    Raises:
        ValueError: If proposal spans are invalid for the given document text.

    """
    if proposal.base_version_id != doc.version_id:
        raise ValueError(
            "base version mismatch:\n  " + _patch_error_context(doc, proposal)
        )

    if proposal.op == PatchOp.NOOP:
        return doc

    if proposal.span_abs is None:
        raise ValueError(
            "span_abs required for non-noop:\n  "
            + _patch_error_context(doc, proposal)
        )

    start, end = proposal.span_abs
    if start < 0 or end < start or end > len(doc.text):
        raise ValueError(
            "span out of bounds:\n  " + _patch_error_context(doc, proposal)
        )

    payload_norm = (
        proposal.payload_norm
        if proposal.payload_norm is not None
        else (proposal.payload or "")
    )
    if proposal.op == PatchOp.REPLACE:
        next_text = doc.text[:start] + payload_norm + doc.text[end:]
    elif proposal.op == PatchOp.INSERT_BEFORE:
        next_text = doc.text[:start] + payload_norm + doc.text[start:]
    elif proposal.op == PatchOp.INSERT_AFTER:
        next_text = doc.text[:end] + payload_norm + doc.text[end:]
    elif proposal.op == PatchOp.DELETE:
        next_text = doc.text[:start] + doc.text[end:]
    else:
        raise ValueError(f"unsupported op: {proposal.op}")

    return DocumentState(next_text, history=doc.history + (proposal.rule_id,))
